kind: Deployment
apiVersion: apps/v1
metadata:
   name: config-server
spec:
   replicas: 2
   selector:
      matchLabels:
         app: config-server
   template:
      metadata:
         name: config-server
         labels:
            app: config-server
      spec:
         containers:
         -  name: config-server
            image: qualitto007/config-server:latest
            imagePullPolicy: Always
            ports:
            -  containerPort: 7777
---
kind: Service
apiVersion: v1
metadata:
   name: config-server-k8srv
   labels:
      app: config-server-k8srv
spec:
   type: NodePort
   ports:
   -  nodePort: 30001
      port: 7777
      targetPort: 7777
   selector:
      app: config-server